name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
    - 'crowdin.yml'
    - 'data/translations/**'
jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-latest]
        include:
          - os: ubuntu-18.04
            extra-cmake-arguments : >-
              -D CMAKE_CXX_FLAGS='-Wall -Wextra -pedantic -Werror'
          - os: ubuntu-20.04
            extra-cmake-arguments : >-
              -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
          - os: windows-latest
            # Enable warnings and exclude third-party headers for them
            extra-cmake-arguments: >-
              -D CMAKE_CXX_FLAGS="/experimental:external /external:anglebrackets /external:W0 /W4 /wd4530 /WX"
              -D CMAKE_CXX_CLANG_TIDY='clang-tidy;--warnings-as-errors=*'
    steps:
    - name: Clone repo
      uses: actions/checkout@v2.3.4

    - name: Install apt packages
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install extra-cmake-modules libqt5x11extras5-dev qttools5-dev qtmultimedia5-dev libtesseract-dev

    - name: Install vcpkg packages
      uses: lukka/run-vcpkg@v7
      if: runner.os == 'Windows'
      with:
        vcpkgArguments: tesseract[cpu-independed] ecm qt5-base qt5-svg qt5-multimedia qt5-winextras qt5-tools --triplet x64-windows
        vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092
      env:
        VCPKG_DISABLE_METRICS: 1

    - name: Build
      uses: lukka/run-cmake@v3.3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: -G Ninja -D WITH_PORTABLE_MODE=ON ${{ matrix.extra-cmake-arguments }}
